name: Publish

on:
  push:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: source

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Commit
      run: |
        git config --local user.email "hello@tylerstewart.ca"
        git config --local user.name "Tyler Stewart"
        git add build
        git commit -m "publish"

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: source

    - name: Publish
      run: |
        npm run publish
